<%@page import="com.prwss.mis.common.util.MISConstants"%>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1" autoFlush="true"%>
<%@ taglib uri="http://struts.apache.org/tags-html" prefix="html"%>
<%@ taglib uri="http://struts.apache.org/tags-bean" prefix="bean"%>
<%@ taglib uri="http://struts.apache.org/tags-logic" prefix="logic"%>
<%@ taglib uri="http://displaytag.sf.net" prefix="display"%>
<%@ taglib uri="http://struts.application-servers.com/layout" prefix="layout" %>


<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<head>
<script type="text/javascript" src="js/codethatcalendarstd.js"></script>
<script type="text/javascript">
		function de_find(){		
			document.trainingSchedulePlanForm.action="trainingSchedulePlanAction.do?method=find&d__mode="+d__mode+"&menuId=HRD007";
			document.trainingSchedulePlanForm.submit();
		}
		function de_modify(){		
			if(d__mode=='ent_modify') { 
				document.trainingSchedulePlanForm.action="trainingSchedulePlanAction.do?method=update&d__mode="+d__mode+"&menuId=HRD007";
				document.trainingSchedulePlanForm.submit();
			}
		}
		function de_remove(){
			if(d__mode=='ent_delete') {
				document.trainingSchedulePlanForm.action="trainingSchedulePlanAction.do?method=delete&d__mode="+d__mode+"&menuId=HRD007";
				document.trainingSchedulePlanForm.submit();
			}
		}
		function de_confirm(){
			if(d__mode=='ent_post') {
				document.trainingSchedulePlanForm.action="trainingSchedulePlanAction.do?method=post&d__mode="+d__mode+"&menuId=HRD007";
				document.trainingSchedulePlanForm.submit();
			}
		}		
		function de_add(){
			if(d__mode=='ent_add') {
				document.trainingSchedulePlanForm.action="trainingSchedulePlanAction.do?method=save&d__mode="+d__mode+"&menuId=HRD007";
				document.trainingSchedulePlanForm.submit();
			}
		}
		    
	</script>
	<link href="css/form.css" rel="stylesheet" type="text/css">
	<link href="css/displaytag.css" rel="stylesheet" type="text/css" />
</head>


<html:html>
<body bgcolor="#6699FF">
	<html:form action="trainingSchedulePlanAction" method="post">
<logic:messagesPresent >
					<div id="errorDiv" class="error displaynone" style="width: 470px%; margin-bottom: 7px; height: 13px;">
 						<html:errors bundle="HR"/>   
					</div>
				</logic:messagesPresent >
				<logic:messagesPresent message="true">
					<div id="successDiv" class="success diplaynone" style="width: 470px;">
						<html:messages id="message" bundle="HR" message="true">
       						<li><bean:write name="message" /></li>
   						</html:messages>
					</div>
				</logic:messagesPresent >
	<br>
	<br>
	<fieldset><legend>Training Schedule Plan</legend>
	<center>
	<br>
	<table>
		<tr>
			<td><label>Location</label></td>
			<td><html:select property="locationId" styleId="locationId" styleClass="cs1" onchange="ajaxFunction('trainingSchedulePlanAction.do?locationId='+this.value+'&method=fetchTrainingPlanId', 'trainingPlanId');">
				<html:option value="">Select Location</html:option>
				<html:options collection="userLocations" labelProperty="label"
					property="value"></html:options>
			</html:select></td>
			
			<td><label>Training Plan Id</label></td>
			<td><html:select property="trainingPlanId" styleClass="cs1" styleId="trainingPlanId" alt="Training Plan ID (Autogenerated)"></html:select></td>
		</tr>
		<tr>
			<td><label>Plan From</label></td>
			<td><html:text property="planFromDate" styleId="planFromDateId" styleClass="ci5"></html:text>
			<!--<input class=ci4 type=button onclick="c1.innerpopup('planFromDateId','calendar_frame');" value="..."/>
			--></td>
			
			<td><label>Plan To</label></td>
			<td><html:text property="planToDate" styleId="planToDateId" styleClass="ci5"></html:text>
				<!--<input class=ci4 type=button onclick="c1.innerpopup('planToDateId','calendar_frame');" value="..."/>
			--></td>
		</tr>
		</table>
	</center>
	</fieldset>
	<fieldset><legend>Training Details</legend>
	<center>
	<table>
		<tr>
		<td><label>Training Name/Objective</label></td>
		<td colspan="3"><html:select property="trainingId" styleId="trainingId" styleClass="cs3" style="width:500px;">
		<html:option value="">Select</html:option>
		<html:options collection="trainingIds" labelName="label" property="value"/>
		</html:select></td>
		</tr>
		<tr>
		<td><label>Number of Trainings</label></td>
		<td><input type="text" id="numberOfTrainingId" class="ci5" onkeypress="return validateKey(event,this,'9@20@2')"/>
		
		</td>
		<td><label>Training Target Destination</label></td>
		<td><input type="text" id="destinationId" class="ci5"/></td>
		</tr>
		<tr>
		<td><label>Training Target Date</label>
		</td>
		<td><input type="text" id="dateId" class="ci5" readonly="true"/></td>
		<td>
		<label>Remarks/Description</label>
		</td>
		<td><input type="text" id="remarksId" class="ci5"/></td>
		<td>
		</tr>
	</table>
	<table>
		<tr>
			<td>
			<div class="divgrid"><layout:datagrid
				styleClass="DATAGRID" property="trainingDetailsDatagrid"
				selectionAllowed="true" multipleSelectionAllowed="false"
				model="datagrid">
			<layout:datagridColumn property="id" title="Id" mode="N,N,N"></layout:datagridColumn>
			<layout:datagridColumn property="trainingObjective" title="Training Objective"></layout:datagridColumn>
			<layout:datagridColumn property="numberOfTraining" title="Number of Trainings"></layout:datagridColumn>
			<layout:datagridColumn property="targetDestination" title="Target Destination"></layout:datagridColumn>
			<layout:datagridColumn property="trainingDate" title="Target Training Starting Date"></layout:datagridColumn>
			<layout:datagridColumn property="remarks" title="Remarks"></layout:datagridColumn>
			</layout:datagrid></div>
			</td>
			<td><img src="images/add.png"
				onclick="StrutsLayout.addDatagridLine('trainingDetailsDatagrid','trainingId~numberOfTrainingId~destinationId~dateId~remarksId')"
				width="20px" /><br>
			<img src="images/delete.png"
				onclick="StrutsLayout.setDatagridLineState('trainingDetailsDatagrid', 'removed')"
				width="20px" /></td>
		</tr>
	</table>
	</center>
	</fieldset>
	<script language="javascript">
	triggerEvent(document.getElementById('locationId'), 'onchange');
	document.getElementById("trainingPlanId").value="<%=request.getAttribute("trainingPlanId")%>";
	</script>
		
</html:form>
</html:html>