<%@page import="com.prwss.mis.common.util.MISConstants"%>
<%@page import="com.prwss.mis.common.util.MisUtility"%>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1" autoFlush="true"%>
<%@ taglib uri="http://struts.apache.org/tags-html" prefix="html"%>
<%@ taglib uri="http://struts.apache.org/tags-bean" prefix="bean"%>
<%@ taglib uri="http://struts.apache.org/tags-logic" prefix="logic"%>
<%@ taglib uri="http://displaytag.sf.net" prefix="display"%>
<%@ taglib uri="http://struts.application-servers.com/layout" prefix="layout" %>


<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<head>
<script type="text/javascript" src="js/codethatcalendarstd.js"></script>
<script type="text/javascript">
		function de_find(){		
			document.trainingManagementForm.action="trainingManagementAction.do?method=find&d__mode="+d__mode+"&menuId=HRD006";
			document.trainingManagementForm.submit();
		}
		function de_modify(){		
			if(d__mode=='ent_modify') { 
				document.trainingManagementForm.action="trainingManagementAction.do?method=update&d__mode="+d__mode+"&menuId=HRD006";
				document.trainingManagementForm.submit();
			}
		}
		function de_remove(){
			if(d__mode=='ent_delete') {
				document.trainingManagementForm.action="trainingManagementAction.do?method=delete&d__mode="+d__mode+"&menuId=HRD006";
				document.trainingManagementForm.submit();
			}
		}
		function de_confirm(){
			if(d__mode=='ent_post') {
				document.trainingManagementForm.action="trainingManagementAction.do?method=post&d__mode="+d__mode+"&menuId=HRD006";
				document.trainingManagementForm.submit();
			}
		}		
		function de_add(){
			if(d__mode=='ent_add') {
				document.trainingManagementForm.action="trainingManagementAction.do?method=save&d__mode="+d__mode+"&menuId=HRD006";
				document.trainingManagementForm.submit();
			}
		}
		    
	</script>
	<link href="css/form.css" rel="stylesheet" type="text/css">
	<link href="css/displaytag.css" rel="stylesheet" type="text/css" />
</head>


<html:html>
<body bgcolor="#6699FF">
<html:form action="trainingManagementAction" method="post">
<logic:messagesPresent >
					<div id="errorDiv" class="error displaynone" style="width: 470px%; margin-bottom: 7px; min-height: 13px;">
 						<html:errors bundle="HR"/>   
					</div>
				</logic:messagesPresent >
				<logic:messagesPresent message="true">
					<div id="successDiv" class="success diplaynone" style="width: 470px;">
						<html:messages id="message" bundle="HR" message="true">
       						<li><bean:write name="message" /></li>
   						</html:messages>
					</div>
				</logic:messagesPresent >
	
	<br>
	<br>
	<fieldset><legend>HR Training Selection</legend>
	<center>
	<br>
	<table>
		<tr>
			<td><label>Location</label></td>
			<td><html:select property="locationId" styleId="locationId" styleClass="cs1" onchange="ajaxFunction('trainingManagementAction.do?locationId='+this.value+'&method=fetchTrainingPlanId', 'trainingPlanId');ajaxFunction('trainingManagementAction.do?locationId='+this.value+'&method=fetchEmployees', 'employeeId');triggerEvent(document.getElementById('trainingPlanId'), 'onchange');">
				<html:option value="">Select Location</html:option>
				<html:options collection="userLocations" labelProperty="label"
					property="value"></html:options>
			</html:select></td>
			
			<td><label>Training Plan Id</label></td>
			<td><html:select property="trainingPlanId" styleClass="cs1" styleId="trainingPlanId" alt="Training Plan ID (Autogenerated)" onchange="ajaxFunction('trainingManagementAction.do?trainingPlanId='+this.value+'&method=fetchTrainingObjective', 'trainingObjectiveId')"></html:select></td>
		</tr>
		<tr>
			<td colspan="3"><label>Training Objective(As Defined Under The Training Plan)</label></td>
			<td><html:select property="trainingObjective" styleId="trainingObjectiveId" styleClass="cs1" ></html:select>
			</td>
		</tr>
		</table>
	</center>
	</fieldset>
	<fieldset><legend>Employees Training Detail</legend>
	<center>
	<table>
		<tr>
		<td><label>Employee Id</label></td>
		<td><select id="employeeId" class="cs1"></select></td>
		<td><label>Employee Training Start Date</label></td>
		<td><input type="text" id="fromDateId" class="ci5" readonly="true"/></td>
		<td><label>Employee Training End Date</label></td>
		<td><input type="text" id="toDateId" class="ci5" readonly="true"/></td>
		</tr>
		<tr>
		<td><label>Training Venue</label>
		</td>
		<td><input type="text" id="trainingVenueId" class="ci5"/></td>
		<td>
		<label>Remarks/Description</label>
		</td>
		<td><input type="text" id="remarksId" class="ci5"/></td>
		<td>
		</tr>
	</table>
	<table>
		<tr>
			<td>
			<div class="divgrid"><layout:datagrid
				styleClass="DATAGRID" property="employeeTrainingDetailDatagrid"
				selectionAllowed="true" multipleSelectionAllowed="false"
				model="datagrid">
			<layout:datagridColumn property="id" title="Id" mode="N,N,N"></layout:datagridColumn>
			<layout:datagridColumn property="employeeId" title="Employee Id" mode="I,I,I"></layout:datagridColumn>
			<layout:datagridColumn property="fromDate" title="Employee Training Start Date"></layout:datagridColumn>
			<layout:datagridColumn property="toDate" title="Employee Training End Date"></layout:datagridColumn>
			<layout:datagridColumn property="trainingVenue" title="Training Venue"></layout:datagridColumn>
			<layout:datagridColumn property="remarks" title="Remarks"></layout:datagridColumn>
			</layout:datagrid></div>
			</td>
			<td><img src="images/add.png"
				onclick="StrutsLayout.addDatagridLine('employeeTrainingDetailDatagrid','employeeId~fromDateId~toDateId~trainingVenueId~remarksId')"
				width="20px" /><br>
			<img src="images/delete.png"
				onclick="StrutsLayout.setDatagridLineState('employeeTrainingDetailDatagrid', 'removed')"
				width="20px" /></td>
		</tr>
	</table>
	</center>
	</fieldset>
	<script language="javascript">
	triggerEvent(document.getElementById('locationId'), 'onchange');
	
	<%if(MisUtility.ifEmpty(request.getAttribute("trainingPlanId"))){%>
	document.getElementById("trainingPlanId").value="<%=request.getAttribute("trainingPlanId")%>";
	triggerEvent(document.getElementById('trainingPlanId'), 'onchange');
	<%}%>
	<%if(MisUtility.ifEmpty(request.getAttribute("trainingObjective"))){%>
	document.getElementById("trainingObjectiveId").value="<%=request.getAttribute("trainingObjective")%>";
	<%}%>
	</script>
		
</html:form>
</html:html>